// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/metrics_mock.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMetricsAgentService is a mock of MetricsAgentService interface.
type MockMetricsAgentService struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsAgentServiceMockRecorder
	isgomock struct{}
}

// MockMetricsAgentServiceMockRecorder is the mock recorder for MockMetricsAgentService.
type MockMetricsAgentServiceMockRecorder struct {
	mock *MockMetricsAgentService
}

// NewMockMetricsAgentService creates a new mock instance.
func NewMockMetricsAgentService(ctrl *gomock.Controller) *MockMetricsAgentService {
	mock := &MockMetricsAgentService{ctrl: ctrl}
	mock.recorder = &MockMetricsAgentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsAgentService) EXPECT() *MockMetricsAgentServiceMockRecorder {
	return m.recorder
}

// Collect mocks base method.
func (m *MockMetricsAgentService) Collect() map[string]map[string]float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Collect")
	ret0, _ := ret[0].(map[string]map[string]float64)
	return ret0
}

// Collect indicates an expected call of Collect.
func (mr *MockMetricsAgentServiceMockRecorder) Collect() *MockMetricsAgentServiceCollectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collect", reflect.TypeOf((*MockMetricsAgentService)(nil).Collect))
	return &MockMetricsAgentServiceCollectCall{Call: call}
}

// MockMetricsAgentServiceCollectCall wrap *gomock.Call
type MockMetricsAgentServiceCollectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMetricsAgentServiceCollectCall) Return(arg0 map[string]map[string]float64) *MockMetricsAgentServiceCollectCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMetricsAgentServiceCollectCall) Do(f func() map[string]map[string]float64) *MockMetricsAgentServiceCollectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMetricsAgentServiceCollectCall) DoAndReturn(f func() map[string]map[string]float64) *MockMetricsAgentServiceCollectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Send mocks base method.
func (m *MockMetricsAgentService) Send(metricType, name string, value float64) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", metricType, name, value)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockMetricsAgentServiceMockRecorder) Send(metricType, name, value any) *MockMetricsAgentServiceSendCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockMetricsAgentService)(nil).Send), metricType, name, value)
	return &MockMetricsAgentServiceSendCall{Call: call}
}

// MockMetricsAgentServiceSendCall wrap *gomock.Call
type MockMetricsAgentServiceSendCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMetricsAgentServiceSendCall) Return(resp *http.Response, err error) *MockMetricsAgentServiceSendCall {
	c.Call = c.Call.Return(resp, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMetricsAgentServiceSendCall) Do(f func(string, string, float64) (*http.Response, error)) *MockMetricsAgentServiceSendCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMetricsAgentServiceSendCall) DoAndReturn(f func(string, string, float64) (*http.Response, error)) *MockMetricsAgentServiceSendCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
