// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/service_mock.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "kialkuz/service-metrics-and-alerting/internal/dto"
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMetricsAgentService is a mock of MetricsAgentService interface.
type MockMetricsAgentService struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsAgentServiceMockRecorder
	isgomock struct{}
}

// MockMetricsAgentServiceMockRecorder is the mock recorder for MockMetricsAgentService.
type MockMetricsAgentServiceMockRecorder struct {
	mock *MockMetricsAgentService
}

// NewMockMetricsAgentService creates a new mock instance.
func NewMockMetricsAgentService(ctrl *gomock.Controller) *MockMetricsAgentService {
	mock := &MockMetricsAgentService{ctrl: ctrl}
	mock.recorder = &MockMetricsAgentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsAgentService) EXPECT() *MockMetricsAgentServiceMockRecorder {
	return m.recorder
}

// CollectMemStats mocks base method.
func (m *MockMetricsAgentService) CollectMemStats() map[string]float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectMemStats")
	ret0, _ := ret[0].(map[string]float64)
	return ret0
}

// CollectMemStats indicates an expected call of CollectMemStats.
func (mr *MockMetricsAgentServiceMockRecorder) CollectMemStats() *MockMetricsAgentServiceCollectMemStatsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectMemStats", reflect.TypeOf((*MockMetricsAgentService)(nil).CollectMemStats))
	return &MockMetricsAgentServiceCollectMemStatsCall{Call: call}
}

// MockMetricsAgentServiceCollectMemStatsCall wrap *gomock.Call
type MockMetricsAgentServiceCollectMemStatsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMetricsAgentServiceCollectMemStatsCall) Return(arg0 map[string]float64) *MockMetricsAgentServiceCollectMemStatsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMetricsAgentServiceCollectMemStatsCall) Do(f func() map[string]float64) *MockMetricsAgentServiceCollectMemStatsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMetricsAgentServiceCollectMemStatsCall) DoAndReturn(f func() map[string]float64) *MockMetricsAgentServiceCollectMemStatsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Send mocks base method.
func (m *MockMetricsAgentService) Send(name string, value dto.Metrics) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", name, value)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockMetricsAgentServiceMockRecorder) Send(name, value any) *MockMetricsAgentServiceSendCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockMetricsAgentService)(nil).Send), name, value)
	return &MockMetricsAgentServiceSendCall{Call: call}
}

// MockMetricsAgentServiceSendCall wrap *gomock.Call
type MockMetricsAgentServiceSendCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMetricsAgentServiceSendCall) Return(arg0 *http.Response, arg1 error) *MockMetricsAgentServiceSendCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMetricsAgentServiceSendCall) Do(f func(string, dto.Metrics) (*http.Response, error)) *MockMetricsAgentServiceSendCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMetricsAgentServiceSendCall) DoAndReturn(f func(string, dto.Metrics) (*http.Response, error)) *MockMetricsAgentServiceSendCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
