// Code generated by MockGen. DO NOT EDIT.
// Source: metrics.go
//
// Generated by this command:
//
//	mockgen -source=metrics.go -destination=mocks/metrics_mock.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	model "kialkuz/service-metrics-and-alerting/internal/model"
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMetricsServerService is a mock of MetricsServerService interface.
type MockMetricsServerService struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsServerServiceMockRecorder
	isgomock struct{}
}

// MockMetricsServerServiceMockRecorder is the mock recorder for MockMetricsServerService.
type MockMetricsServerServiceMockRecorder struct {
	mock *MockMetricsServerService
}

// NewMockMetricsServerService creates a new mock instance.
func NewMockMetricsServerService(ctrl *gomock.Controller) *MockMetricsServerService {
	mock := &MockMetricsServerService{ctrl: ctrl}
	mock.recorder = &MockMetricsServerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsServerService) EXPECT() *MockMetricsServerServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockMetricsServerService) Get(metricType, name string) (*model.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", metricType, name)
	ret0, _ := ret[0].(*model.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockMetricsServerServiceMockRecorder) Get(metricType, name any) *MockMetricsServerServiceGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMetricsServerService)(nil).Get), metricType, name)
	return &MockMetricsServerServiceGetCall{Call: call}
}

// MockMetricsServerServiceGetCall wrap *gomock.Call
type MockMetricsServerServiceGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMetricsServerServiceGetCall) Return(arg0 *model.Metrics, arg1 error) *MockMetricsServerServiceGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMetricsServerServiceGetCall) Do(f func(string, string) (*model.Metrics, error)) *MockMetricsServerServiceGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMetricsServerServiceGetCall) DoAndReturn(f func(string, string) (*model.Metrics, error)) *MockMetricsServerServiceGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetList mocks base method.
func (m *MockMetricsServerService) GetList() ([]model.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList")
	ret0, _ := ret[0].([]model.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetList indicates an expected call of GetList.
func (mr *MockMetricsServerServiceMockRecorder) GetList() *MockMetricsServerServiceGetListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockMetricsServerService)(nil).GetList))
	return &MockMetricsServerServiceGetListCall{Call: call}
}

// MockMetricsServerServiceGetListCall wrap *gomock.Call
type MockMetricsServerServiceGetListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMetricsServerServiceGetListCall) Return(arg0 []model.Metrics, arg1 error) *MockMetricsServerServiceGetListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMetricsServerServiceGetListCall) Do(f func() ([]model.Metrics, error)) *MockMetricsServerServiceGetListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMetricsServerServiceGetListCall) DoAndReturn(f func() ([]model.Metrics, error)) *MockMetricsServerServiceGetListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m *MockMetricsServerService) Save(name model.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockMetricsServerServiceMockRecorder) Save(name any) *MockMetricsServerServiceSaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockMetricsServerService)(nil).Save), name)
	return &MockMetricsServerServiceSaveCall{Call: call}
}

// MockMetricsServerServiceSaveCall wrap *gomock.Call
type MockMetricsServerServiceSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMetricsServerServiceSaveCall) Return(arg0 error) *MockMetricsServerServiceSaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMetricsServerServiceSaveCall) Do(f func(model.Metrics) error) *MockMetricsServerServiceSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMetricsServerServiceSaveCall) DoAndReturn(f func(model.Metrics) error) *MockMetricsServerServiceSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockMetricsAgentService is a mock of MetricsAgentService interface.
type MockMetricsAgentService struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsAgentServiceMockRecorder
	isgomock struct{}
}

// MockMetricsAgentServiceMockRecorder is the mock recorder for MockMetricsAgentService.
type MockMetricsAgentServiceMockRecorder struct {
	mock *MockMetricsAgentService
}

// NewMockMetricsAgentService creates a new mock instance.
func NewMockMetricsAgentService(ctrl *gomock.Controller) *MockMetricsAgentService {
	mock := &MockMetricsAgentService{ctrl: ctrl}
	mock.recorder = &MockMetricsAgentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsAgentService) EXPECT() *MockMetricsAgentServiceMockRecorder {
	return m.recorder
}

// Collect mocks base method.
func (m *MockMetricsAgentService) Collect() map[string]map[string]float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Collect")
	ret0, _ := ret[0].(map[string]map[string]float64)
	return ret0
}

// Collect indicates an expected call of Collect.
func (mr *MockMetricsAgentServiceMockRecorder) Collect() *MockMetricsAgentServiceCollectCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Collect", reflect.TypeOf((*MockMetricsAgentService)(nil).Collect))
	return &MockMetricsAgentServiceCollectCall{Call: call}
}

// MockMetricsAgentServiceCollectCall wrap *gomock.Call
type MockMetricsAgentServiceCollectCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMetricsAgentServiceCollectCall) Return(arg0 map[string]map[string]float64) *MockMetricsAgentServiceCollectCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMetricsAgentServiceCollectCall) Do(f func() map[string]map[string]float64) *MockMetricsAgentServiceCollectCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMetricsAgentServiceCollectCall) DoAndReturn(f func() map[string]map[string]float64) *MockMetricsAgentServiceCollectCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Send mocks base method.
func (m *MockMetricsAgentService) Send(metricType, name string, value float64) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", metricType, name, value)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockMetricsAgentServiceMockRecorder) Send(metricType, name, value any) *MockMetricsAgentServiceSendCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockMetricsAgentService)(nil).Send), metricType, name, value)
	return &MockMetricsAgentServiceSendCall{Call: call}
}

// MockMetricsAgentServiceSendCall wrap *gomock.Call
type MockMetricsAgentServiceSendCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMetricsAgentServiceSendCall) Return(resp *http.Response, err error) *MockMetricsAgentServiceSendCall {
	c.Call = c.Call.Return(resp, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMetricsAgentServiceSendCall) Do(f func(string, string, float64) (*http.Response, error)) *MockMetricsAgentServiceSendCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMetricsAgentServiceSendCall) DoAndReturn(f func(string, string, float64) (*http.Response, error)) *MockMetricsAgentServiceSendCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
