// Code generated by MockGen. DO NOT EDIT.
// Source: metrics_service.go
//
// Generated by this command:
//
//	mockgen -source=metrics_service.go -destination=mocks/metrics_service_mock.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "kialkuz/service-metrics-and-alerting/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMetricsRepository is a mock of MetricsRepository interface.
type MockMetricsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsRepositoryMockRecorder
	isgomock struct{}
}

// MockMetricsRepositoryMockRecorder is the mock recorder for MockMetricsRepository.
type MockMetricsRepositoryMockRecorder struct {
	mock *MockMetricsRepository
}

// NewMockMetricsRepository creates a new mock instance.
func NewMockMetricsRepository(ctrl *gomock.Controller) *MockMetricsRepository {
	mock := &MockMetricsRepository{ctrl: ctrl}
	mock.recorder = &MockMetricsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsRepository) EXPECT() *MockMetricsRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockMetricsRepository) Add(ctx context.Context, typeValue, name string, value float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, typeValue, name, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockMetricsRepositoryMockRecorder) Add(ctx, typeValue, name, value any) *MockMetricsRepositoryAddCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockMetricsRepository)(nil).Add), ctx, typeValue, name, value)
	return &MockMetricsRepositoryAddCall{Call: call}
}

// MockMetricsRepositoryAddCall wrap *gomock.Call
type MockMetricsRepositoryAddCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMetricsRepositoryAddCall) Return(arg0 error) *MockMetricsRepositoryAddCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMetricsRepositoryAddCall) Do(f func(context.Context, string, string, float64) error) *MockMetricsRepositoryAddCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMetricsRepositoryAddCall) DoAndReturn(f func(context.Context, string, string, float64) error) *MockMetricsRepositoryAddCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddList mocks base method.
func (m *MockMetricsRepository) AddList(ctx context.Context, metrics []model.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddList", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddList indicates an expected call of AddList.
func (mr *MockMetricsRepositoryMockRecorder) AddList(ctx, metrics any) *MockMetricsRepositoryAddListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddList", reflect.TypeOf((*MockMetricsRepository)(nil).AddList), ctx, metrics)
	return &MockMetricsRepositoryAddListCall{Call: call}
}

// MockMetricsRepositoryAddListCall wrap *gomock.Call
type MockMetricsRepositoryAddListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMetricsRepositoryAddListCall) Return(arg0 error) *MockMetricsRepositoryAddListCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMetricsRepositoryAddListCall) Do(f func(context.Context, []model.Metrics) error) *MockMetricsRepositoryAddListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMetricsRepositoryAddListCall) DoAndReturn(f func(context.Context, []model.Metrics) error) *MockMetricsRepositoryAddListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockMetricsRepository) Get(ctx context.Context, metricType, name string) (*model.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, metricType, name)
	ret0, _ := ret[0].(*model.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockMetricsRepositoryMockRecorder) Get(ctx, metricType, name any) *MockMetricsRepositoryGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMetricsRepository)(nil).Get), ctx, metricType, name)
	return &MockMetricsRepositoryGetCall{Call: call}
}

// MockMetricsRepositoryGetCall wrap *gomock.Call
type MockMetricsRepositoryGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMetricsRepositoryGetCall) Return(arg0 *model.Metrics, arg1 error) *MockMetricsRepositoryGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMetricsRepositoryGetCall) Do(f func(context.Context, string, string) (*model.Metrics, error)) *MockMetricsRepositoryGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMetricsRepositoryGetCall) DoAndReturn(f func(context.Context, string, string) (*model.Metrics, error)) *MockMetricsRepositoryGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetList mocks base method.
func (m *MockMetricsRepository) GetList(ctx context.Context) ([]model.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", ctx)
	ret0, _ := ret[0].([]model.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetList indicates an expected call of GetList.
func (mr *MockMetricsRepositoryMockRecorder) GetList(ctx any) *MockMetricsRepositoryGetListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockMetricsRepository)(nil).GetList), ctx)
	return &MockMetricsRepositoryGetListCall{Call: call}
}

// MockMetricsRepositoryGetListCall wrap *gomock.Call
type MockMetricsRepositoryGetListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMetricsRepositoryGetListCall) Return(arg0 []model.Metrics, arg1 error) *MockMetricsRepositoryGetListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMetricsRepositoryGetListCall) Do(f func(context.Context) ([]model.Metrics, error)) *MockMetricsRepositoryGetListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMetricsRepositoryGetListCall) DoAndReturn(f func(context.Context) ([]model.Metrics, error)) *MockMetricsRepositoryGetListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SaveList mocks base method.
func (m *MockMetricsRepository) SaveList(ctx context.Context, metricsForInsert, metricsForUpdate []model.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveList", ctx, metricsForInsert, metricsForUpdate)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveList indicates an expected call of SaveList.
func (mr *MockMetricsRepositoryMockRecorder) SaveList(ctx, metricsForInsert, metricsForUpdate any) *MockMetricsRepositorySaveListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveList", reflect.TypeOf((*MockMetricsRepository)(nil).SaveList), ctx, metricsForInsert, metricsForUpdate)
	return &MockMetricsRepositorySaveListCall{Call: call}
}

// MockMetricsRepositorySaveListCall wrap *gomock.Call
type MockMetricsRepositorySaveListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMetricsRepositorySaveListCall) Return(arg0 error) *MockMetricsRepositorySaveListCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMetricsRepositorySaveListCall) Do(f func(context.Context, []model.Metrics, []model.Metrics) error) *MockMetricsRepositorySaveListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMetricsRepositorySaveListCall) DoAndReturn(f func(context.Context, []model.Metrics, []model.Metrics) error) *MockMetricsRepositorySaveListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateByTypeAndName mocks base method.
func (m *MockMetricsRepository) UpdateByTypeAndName(ctx context.Context, value float64, metricType, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByTypeAndName", ctx, value, metricType, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByTypeAndName indicates an expected call of UpdateByTypeAndName.
func (mr *MockMetricsRepositoryMockRecorder) UpdateByTypeAndName(ctx, value, metricType, name any) *MockMetricsRepositoryUpdateByTypeAndNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByTypeAndName", reflect.TypeOf((*MockMetricsRepository)(nil).UpdateByTypeAndName), ctx, value, metricType, name)
	return &MockMetricsRepositoryUpdateByTypeAndNameCall{Call: call}
}

// MockMetricsRepositoryUpdateByTypeAndNameCall wrap *gomock.Call
type MockMetricsRepositoryUpdateByTypeAndNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMetricsRepositoryUpdateByTypeAndNameCall) Return(arg0 error) *MockMetricsRepositoryUpdateByTypeAndNameCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMetricsRepositoryUpdateByTypeAndNameCall) Do(f func(context.Context, float64, string, string) error) *MockMetricsRepositoryUpdateByTypeAndNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMetricsRepositoryUpdateByTypeAndNameCall) DoAndReturn(f func(context.Context, float64, string, string) error) *MockMetricsRepositoryUpdateByTypeAndNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
