// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/service_mock.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "kialkuz/service-metrics-and-alerting/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMetricsServerService is a mock of MetricsServerService interface.
type MockMetricsServerService struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsServerServiceMockRecorder
	isgomock struct{}
}

// MockMetricsServerServiceMockRecorder is the mock recorder for MockMetricsServerService.
type MockMetricsServerServiceMockRecorder struct {
	mock *MockMetricsServerService
}

// NewMockMetricsServerService creates a new mock instance.
func NewMockMetricsServerService(ctrl *gomock.Controller) *MockMetricsServerService {
	mock := &MockMetricsServerService{ctrl: ctrl}
	mock.recorder = &MockMetricsServerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsServerService) EXPECT() *MockMetricsServerServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockMetricsServerService) Get(ctx context.Context, metricType, name string) (*model.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, metricType, name)
	ret0, _ := ret[0].(*model.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockMetricsServerServiceMockRecorder) Get(ctx, metricType, name any) *MockMetricsServerServiceGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMetricsServerService)(nil).Get), ctx, metricType, name)
	return &MockMetricsServerServiceGetCall{Call: call}
}

// MockMetricsServerServiceGetCall wrap *gomock.Call
type MockMetricsServerServiceGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMetricsServerServiceGetCall) Return(arg0 *model.Metrics, arg1 error) *MockMetricsServerServiceGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMetricsServerServiceGetCall) Do(f func(context.Context, string, string) (*model.Metrics, error)) *MockMetricsServerServiceGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMetricsServerServiceGetCall) DoAndReturn(f func(context.Context, string, string) (*model.Metrics, error)) *MockMetricsServerServiceGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetList mocks base method.
func (m *MockMetricsServerService) GetList(ctx context.Context) ([]model.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", ctx)
	ret0, _ := ret[0].([]model.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetList indicates an expected call of GetList.
func (mr *MockMetricsServerServiceMockRecorder) GetList(ctx any) *MockMetricsServerServiceGetListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockMetricsServerService)(nil).GetList), ctx)
	return &MockMetricsServerServiceGetListCall{Call: call}
}

// MockMetricsServerServiceGetListCall wrap *gomock.Call
type MockMetricsServerServiceGetListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMetricsServerServiceGetListCall) Return(arg0 []model.Metrics, arg1 error) *MockMetricsServerServiceGetListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMetricsServerServiceGetListCall) Do(f func(context.Context) ([]model.Metrics, error)) *MockMetricsServerServiceGetListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMetricsServerServiceGetListCall) DoAndReturn(f func(context.Context) ([]model.Metrics, error)) *MockMetricsServerServiceGetListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m *MockMetricsServerService) Save(ctx context.Context, name model.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockMetricsServerServiceMockRecorder) Save(ctx, name any) *MockMetricsServerServiceSaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockMetricsServerService)(nil).Save), ctx, name)
	return &MockMetricsServerServiceSaveCall{Call: call}
}

// MockMetricsServerServiceSaveCall wrap *gomock.Call
type MockMetricsServerServiceSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMetricsServerServiceSaveCall) Return(arg0 error) *MockMetricsServerServiceSaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMetricsServerServiceSaveCall) Do(f func(context.Context, model.Metrics) error) *MockMetricsServerServiceSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMetricsServerServiceSaveCall) DoAndReturn(f func(context.Context, model.Metrics) error) *MockMetricsServerServiceSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateByTypeAndName mocks base method.
func (m *MockMetricsServerService) UpdateByTypeAndName(ctx context.Context, newValue float64, mType, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByTypeAndName", ctx, newValue, mType, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByTypeAndName indicates an expected call of UpdateByTypeAndName.
func (mr *MockMetricsServerServiceMockRecorder) UpdateByTypeAndName(ctx, newValue, mType, name any) *MockMetricsServerServiceUpdateByTypeAndNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByTypeAndName", reflect.TypeOf((*MockMetricsServerService)(nil).UpdateByTypeAndName), ctx, newValue, mType, name)
	return &MockMetricsServerServiceUpdateByTypeAndNameCall{Call: call}
}

// MockMetricsServerServiceUpdateByTypeAndNameCall wrap *gomock.Call
type MockMetricsServerServiceUpdateByTypeAndNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMetricsServerServiceUpdateByTypeAndNameCall) Return(arg0 error) *MockMetricsServerServiceUpdateByTypeAndNameCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMetricsServerServiceUpdateByTypeAndNameCall) Do(f func(context.Context, float64, string, string) error) *MockMetricsServerServiceUpdateByTypeAndNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMetricsServerServiceUpdateByTypeAndNameCall) DoAndReturn(f func(context.Context, float64, string, string) error) *MockMetricsServerServiceUpdateByTypeAndNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
