// Code generated by MockGen. DO NOT EDIT.
// Source: metrics.go
//
// Generated by this command:
//
//	mockgen -source=metrics.go -destination=mocks/metrics_mock.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	model "kialkuz/service-metrics-and-alerting/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMetricsDBRepository is a mock of MetricsDBRepository interface.
type MockMetricsDBRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsDBRepositoryMockRecorder
	isgomock struct{}
}

// MockMetricsDBRepositoryMockRecorder is the mock recorder for MockMetricsDBRepository.
type MockMetricsDBRepositoryMockRecorder struct {
	mock *MockMetricsDBRepository
}

// NewMockMetricsDBRepository creates a new mock instance.
func NewMockMetricsDBRepository(ctrl *gomock.Controller) *MockMetricsDBRepository {
	mock := &MockMetricsDBRepository{ctrl: ctrl}
	mock.recorder = &MockMetricsDBRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsDBRepository) EXPECT() *MockMetricsDBRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockMetricsDBRepository) Add(ctx context.Context, typeValue, name string, value float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, typeValue, name, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockMetricsDBRepositoryMockRecorder) Add(ctx, typeValue, name, value any) *MockMetricsDBRepositoryAddCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockMetricsDBRepository)(nil).Add), ctx, typeValue, name, value)
	return &MockMetricsDBRepositoryAddCall{Call: call}
}

// MockMetricsDBRepositoryAddCall wrap *gomock.Call
type MockMetricsDBRepositoryAddCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMetricsDBRepositoryAddCall) Return(arg0 error) *MockMetricsDBRepositoryAddCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMetricsDBRepositoryAddCall) Do(f func(context.Context, string, string, float64) error) *MockMetricsDBRepositoryAddCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMetricsDBRepositoryAddCall) DoAndReturn(f func(context.Context, string, string, float64) error) *MockMetricsDBRepositoryAddCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Close mocks base method.
func (m *MockMetricsDBRepository) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockMetricsDBRepositoryMockRecorder) Close() *MockMetricsDBRepositoryCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMetricsDBRepository)(nil).Close))
	return &MockMetricsDBRepositoryCloseCall{Call: call}
}

// MockMetricsDBRepositoryCloseCall wrap *gomock.Call
type MockMetricsDBRepositoryCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMetricsDBRepositoryCloseCall) Return() *MockMetricsDBRepositoryCloseCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMetricsDBRepositoryCloseCall) Do(f func()) *MockMetricsDBRepositoryCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMetricsDBRepositoryCloseCall) DoAndReturn(f func()) *MockMetricsDBRepositoryCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockMetricsDBRepository) Get(ctx context.Context, metricType, name string) (*model.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, metricType, name)
	ret0, _ := ret[0].(*model.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockMetricsDBRepositoryMockRecorder) Get(ctx, metricType, name any) *MockMetricsDBRepositoryGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMetricsDBRepository)(nil).Get), ctx, metricType, name)
	return &MockMetricsDBRepositoryGetCall{Call: call}
}

// MockMetricsDBRepositoryGetCall wrap *gomock.Call
type MockMetricsDBRepositoryGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMetricsDBRepositoryGetCall) Return(arg0 *model.Metrics, arg1 error) *MockMetricsDBRepositoryGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMetricsDBRepositoryGetCall) Do(f func(context.Context, string, string) (*model.Metrics, error)) *MockMetricsDBRepositoryGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMetricsDBRepositoryGetCall) DoAndReturn(f func(context.Context, string, string) (*model.Metrics, error)) *MockMetricsDBRepositoryGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetList mocks base method.
func (m *MockMetricsDBRepository) GetList(ctx context.Context) ([]model.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", ctx)
	ret0, _ := ret[0].([]model.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetList indicates an expected call of GetList.
func (mr *MockMetricsDBRepositoryMockRecorder) GetList(ctx any) *MockMetricsDBRepositoryGetListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockMetricsDBRepository)(nil).GetList), ctx)
	return &MockMetricsDBRepositoryGetListCall{Call: call}
}

// MockMetricsDBRepositoryGetListCall wrap *gomock.Call
type MockMetricsDBRepositoryGetListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMetricsDBRepositoryGetListCall) Return(arg0 []model.Metrics, arg1 error) *MockMetricsDBRepositoryGetListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMetricsDBRepositoryGetListCall) Do(f func(context.Context) ([]model.Metrics, error)) *MockMetricsDBRepositoryGetListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMetricsDBRepositoryGetListCall) DoAndReturn(f func(context.Context) ([]model.Metrics, error)) *MockMetricsDBRepositoryGetListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateByTypeAndName mocks base method.
func (m *MockMetricsDBRepository) UpdateByTypeAndName(ctx context.Context, value float64, metricType, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByTypeAndName", ctx, value, metricType, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByTypeAndName indicates an expected call of UpdateByTypeAndName.
func (mr *MockMetricsDBRepositoryMockRecorder) UpdateByTypeAndName(ctx, value, metricType, name any) *MockMetricsDBRepositoryUpdateByTypeAndNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByTypeAndName", reflect.TypeOf((*MockMetricsDBRepository)(nil).UpdateByTypeAndName), ctx, value, metricType, name)
	return &MockMetricsDBRepositoryUpdateByTypeAndNameCall{Call: call}
}

// MockMetricsDBRepositoryUpdateByTypeAndNameCall wrap *gomock.Call
type MockMetricsDBRepositoryUpdateByTypeAndNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMetricsDBRepositoryUpdateByTypeAndNameCall) Return(arg0 error) *MockMetricsDBRepositoryUpdateByTypeAndNameCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMetricsDBRepositoryUpdateByTypeAndNameCall) Do(f func(context.Context, float64, string, string) error) *MockMetricsDBRepositoryUpdateByTypeAndNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMetricsDBRepositoryUpdateByTypeAndNameCall) DoAndReturn(f func(context.Context, float64, string, string) error) *MockMetricsDBRepositoryUpdateByTypeAndNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
